In [7]:
import numpy as np
ar=numpy.array([0,1,2,3,4])
ar

array([0, 1, 2, 3, 4])

In [3]:
type(ar)

numpy.ndarray

In [10]:
# 시간 복잡도(CPU) : 연산 결과 출력까지 수행되는 라인 갯수 , O(n)
# 공간 복잡도(MEM) 


data=list(range(0,10))
ans=[]
for d in data:
    ans.append(2*d)     # O(10)
print(ans)

# 벡터화 연산 - for 구문 사용x, 빠른 연산 속도
x=np.array(data)
x*2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a2=[1,2,3]
b2=[4,5,6]

2*a2+b2  # [1,2,3,1,2,3,4,5,6]
2*a+b # array([6,9,12])
a2==2  # False
a==2   # array([False, True, False])
#a2>2   #error
a>2    # array([False, False, True])

array([False, False,  True])

In [20]:
m=np.array([[[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12]],
         [[31,32,33,34],
         [35,36,37,38],
         [39,310,311,312]]])
len(m)
len(m[0])
len(m[0][0])

4

In [25]:
import numpy as np
m=np.array([[0,1,2], [3,4,5]])

#배열의 차원
m.ndim   

# 배열의 크기
#m.shape

2

In [27]:
import numpy as np
m=np.array([[[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12]],
         [[31,32,33,34],
         [35,36,37,38],
         [39,310,311,312]]]) 
#m.ndim
m.shape

(2, 3, 4)

In [83]:
a=[3,1,-2,2,1,-3,-2,0,-7]

list=[]
for i in range(0,7):
    sum=a[i]*a[i+1]*a[i+2]
    list.append(sum)

maxValue = list[0]
for i in range(1, len(list)):
    if maxValue < list[i]:
        maxValue = list[i]
print(maxValue)

6


In [86]:
b=[[3,1,-2],[2,1,-3],[-2,0,-7]]


list=[]
for i in range(0,2):
    mul=b[i][i]*b[i][i+1]*b[i+1][i]*b[i+1][i+1]
    list.append(mul)

maxValue = list[0]
for i in range(1, len(list)):
    if maxValue < list[i]:
        maxValue = list[i]
max=maxValue


In [97]:
import numpy as np
ar=np.array([[1,2,3,4], [5,6,7,8]])
# ar[0,:]    # 첫번째 행 전체 array([1,2,3,4])
# ar[:,1]    # 두번째 열 전체 array([2,6])
# ar[1,1:]   # 두번째 행, 두번째 열~마지막  array([6,7,8])
ar[:,:2]
ar[0][0]
ar[1,1]
ar[-1,1]

6

In [104]:
import numpy as np
ar=np.array([2,3,4,5])
bidx=np.array([True, True, False, True])

# ar[bidx]
# ar != 4
# ar[ar != 4]
# ar[ar%2==0]
# ar[ar>3]


array([4, 5])

In [106]:
import numpy as np
ar=np.array([2,3,4,5])
idx=np.array([0,3])
idx2=np.array([0,0,1,1])

#ar[idx]     # array([2, 5])
ar[idx2]

array([2, 2, 3, 3])

In [111]:
import numpy as np
ar=np.array([[1,2,3,4], [5,6,7,8]])
ar[:,[0,3]]
ar[:,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [115]:
import numpy as np
ar=np.array([[1,2,3,4], 
             [15,16,17,18],
             [25,26,27,28], 
             [35,36,37,38]])

ar[2,:]
ar[[2,0],:] 
ar[[2,0,-1],:]

array([[25, 26, 27, 28],
       [ 1,  2,  3,  4],
       [35, 36, 37, 38]])

In [135]:
import pandas as pd
csvTest=pd.read_csv('test_csv.csv')
csvTest

ID LAST_NAME  AGE
0   1       KIM   25
1   2       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO   30

In [134]:
import pandas as pd
text=pd.read_csv("test_text.txt")
text

ID|LAST_NAME|AGE
0         1|KIM|25
1         2|LEE|22
2        3|PARK|33
3        4|CHOI|24
4         5|CHO|30