In [1]:
import numpy as np


In [8]:
# MLP 없이 신경망 구현
# 다차원배열
x=np.array([1,2,3,4])
np.ndim(x)
x.shape

(4,)

In [9]:
y=np.array([[1,2],[3,4],[5,6]])
np.ndim(y)
y.shape

(3, 2)

In [11]:
# 행렬 내적
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
np.dot(x,y)
np.dot(y,x)

array([[23, 34],
       [31, 46]])

In [14]:
# 신경망 내적 (층 2개)
x=np.array([1,2])
w=np.array([[1,3,5],[2,4,6]])
np.dot(x,w)

array([ 5, 11, 17])

In [18]:
def sig(x):
    return 1/(1+np.exp(-x))

In [33]:
# 신경망 내적 (층 3개)
x=np.array([1.0,0.5])
w1=np.array([[0.1,0.3,0.5],
            [0.2,0.4,0.6]])
b1=np.array([0.1,0.2,0.3])
h1=np.dot(x,w1)+b1
z1=sig(h1)

w2=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
b2=np.array([0.1,0.2])
h2=np.dot(z1,w2)+b2
z2=sig(h2)

w3=np.array([[0.1,0.2],[0.2,0.3]])
b3=np.array([0.1,0.2])
h3=np.dot(z2,w3)+b3
print(h3)

[0.31682708 0.55655308]


In [ ]:
## softmax 함수

In [36]:
score=np.array([20,10,1])
# 지수함수
exp_score=np.exp(score)
# 지수함수의 합
sum_exp_score=np.sum(exp_score)

y=exp_score/sum_exp_score

array([9.99954597e-01, 4.53978684e-05, 5.60254205e-09])

In [37]:
## reLu 함수 구현
def reLu(data):
    if data>=0:
        return data
    else:
        return 0

In [38]:
# 신경망 내적 2 (층 3개)
x=np.array([2,5])
w1=np.array([[1,2,3],
            [4,5,6]])
b1=np.array([0.1,0.2,0.3])
h1=np.dot(x,w1)+b1
z1=reLu(h1)

w2=np.array([[1,2],[3,4],[5,6]])
b2=np.array([0.1,0.2])
h2=np.dot(z1,w2)+b2
z2=reLu(h2)

w3=np.array([1,2])
b3=np.array([0.1])
h3=np.dot(z2,w3)+b3
print(h3)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

array([0.57444252, 0.66818777, 0.75026011])