In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data=np.array([[10,-10,2],
              [5,0,6],
              [0,7,4]])
data

array([[ 10, -10,   2],
       [  5,   0,   6],
       [  0,   7,   4]])

In [7]:
data.max(axis=0)

array([10,  7,  6])

In [8]:
data.min(axis=0)

array([  0, -10,   2])

In [9]:
data.max(axis=0)-data.min(axis=0)

array([10, 17,  4])

In [13]:
data_mm=(data-data.min(axis=0))/data.max(axis=0)-data.min(axis=0)

In [14]:
mms=MinMaxScaler()
mms.fit_transform(data)

array([[1.        , 0.        , 0.        ],
       [0.5       , 0.58823529, 1.        ],
       [0.        , 1.        , 0.5       ]])

In [15]:
from sklearn.preprocessing import minmax_scale

In [16]:
minmax_scale(data,axis=0)

array([[1.        , 0.        , 0.        ],
       [0.5       , 0.58823529, 1.        ],
       [0.        , 1.        , 0.5       ]])

In [17]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import Binarizer 

In [18]:
data

array([[ 10, -10,   2],
       [  5,   0,   6],
       [  0,   7,   4]])

In [21]:
bina=Binarizer().fit(data)

In [20]:
Binarizer(threshold=5).fit(data)

Binarizer(copy=True, threshold=5)

In [22]:
bina.transform(data)

array([[1, 0, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [24]:
bina5=Binarizer(threshold=5).fit(data)


In [25]:
bina5.transform(data)

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [26]:
from sklearn.preprocessing import binarize

In [27]:
data=np.array([[10,-10,2],
              [5,0,6],
              [0,7,4]])

In [29]:
binarize(data,threshold=5)

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [33]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import OneHotEncoder 

In [38]:
data=np.array([[0,0,0],
              [0,1,1],
              [0,2,2],
              [1,0,3],
              [1,1,4]])

In [39]:
ohe=OneHotEncoder()

In [40]:
ohe.fit(data)

C:\Users\student\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [41]:
ohe.active_features_

C:\Users\student\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:100: DeprecationWarning: The ``active_features_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [42]:
ohe.n_values_

C:\Users\student\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:100: DeprecationWarning: The ``n_values_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


array([2, 3, 5])

In [43]:
ohe.feature_indices_

C:\Users\student\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:100: DeprecationWarning: The ``feature_indices_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


array([ 0,  2,  5, 10], dtype=int32)

In [44]:

data2=np.array([[1,2,3]])

In [45]:
ohe.transform(data2)

<1x10 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [46]:
ohe.transform(data2).toarray()

array([[0., 1., 0., 0., 1., 0., 0., 0., 1., 0.]])

In [47]:
df = pd.DataFrame({'C1': np.random.randn(20),

   'C2': ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a',

   'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b']})
df

C1 C2
0  -0.277210  a
1  -0.984791  a
2  -1.674038  a
3   0.121659  a
4  -0.922861  a
5  -1.222850  a
6  -0.681192  a
7   0.484530  a
8   0.368997  a
9   0.816975  a
10 -0.318110  b
11  0.959385  b
12 -0.715827  b
13 -1.330698  b
14  0.455220  b
15  1.278751  b
16  1.046351  b
17  0.469803  b
18  0.358513  b
19  1.722230  b

In [56]:
import numpy as np
import pandas as pd
np.random.seed(42)
np.random.randn(1)

array([0.49671415])

In [57]:
df = pd.DataFrame({'C1': np.random.randn(20),

   'C2': ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a',

   'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b']})

df.C1.min()

-1.913280244657798

In [58]:
df.C1.max()

1.5792128155073915

In [65]:
bins=np.linspace(df.C1.min(),df.C1.max(),10)
bins

array([-1.91328024, -1.52522546, -1.13717068, -0.74911589, -0.36106111,
        0.02699368,  0.41504846,  0.80310325,  1.19115803,  1.57921282])

In [61]:
df.C1

0    -0.138264
1     0.647689
2     1.523030
3    -0.234153
4    -0.234137
5     1.579213
6     0.767435
7    -0.469474
8     0.542560
9    -0.463418
10   -0.465730
11    0.241962
12   -1.913280
13   -1.724918
14   -0.562288
15   -1.012831
16    0.314247
17   -0.908024
18   -1.412304
19    1.465649
Name: C1, dtype: float64

In [64]:
df['C1_bin']=np.digitize(df.C1,bins)
df

C1 C2  C1_bin
0  -0.138264  a       5
1   0.647689  a       7
2   1.523030  a       9
3  -0.234153  a       5
4  -0.234137  a       5
5   1.579213  a      10
6   0.767435  a       7
7  -0.469474  a       4
8   0.542560  a       7
9  -0.463418  a       4
10 -0.465730  b       4
11  0.241962  b       6
12 -1.913280  b       1
13 -1.724918  b       1
14 -0.562288  b       4
15 -1.012831  b       3
16  0.314247  b       6
17 -0.908024  b       3
18 -1.412304  b       2
19  1.465649  b       9

In [66]:
df.C1_bin

0      5
1      7
2      9
3      5
4      5
5     10
6      7
7      4
8      7
9      4
10     4
11     6
12     1
13     1
14     4
15     3
16     6
17     3
18     2
19     9
Name: C1_bin, dtype: int64

In [68]:
df.groupby('C1_bin')['C1'].size()

C1_bin
1     2
2     1
3     2
4     4
5     3
6     2
7     3
9     2
10    1
Name: C1, dtype: int64

In [69]:
df.groupby('C1_bin')['C1'].mean()

C1_bin
1    -1.819099
2    -1.412304
3    -0.960428
4    -0.490227
5    -0.202185
6     0.278105
7     0.652561
9     1.494339
10    1.579213
Name: C1, dtype: float64

In [70]:
df.groupby('C1_bin')['C1'].std()

C1_bin
1     0.133192
2          NaN
3     0.074110
4     0.048105
5     0.055357
6     0.051113
7     0.112516
9     0.040575
10         NaN
Name: C1, dtype: float64

In [71]:
df.groupby('C1_bin')['C2'].value_counts()

C1_bin  C2
1       b     2
2       b     1
3       b     2
4       a     2
        b     2
5       a     3
6       b     2
7       a     3
9       a     1
        b     1
10      a     1
Name: C2, dtype: int64

In [73]:
df[df["C1_bin"]==4]

C1 C2  C1_bin
7  -0.469474  a       4
9  -0.463418  a       4
10 -0.465730  b       4
14 -0.562288  b       4

In [75]:
pd.get_dummies(df['C1_bin'],prefix='C1')

C1_1  C1_2  C1_3  C1_4  C1_5  C1_6  C1_7  C1_9  C1_10
0      0     0     0     0     1     0     0     0      0
1      0     0     0     0     0     0     1     0      0
2      0     0     0     0     0     0     0     1      0
3      0     0     0     0     1     0     0     0      0
4      0     0     0     0     1     0     0     0      0
5      0     0     0     0     0     0     0     0      1
6      0     0     0     0     0     0     1     0      0
7      0     0     0     1     0     0     0     0      0
8      0     0     0     0     0     0     1     0      0
9      0     0     0     1     0     0     0     0      0
10     0     0     0     1     0     0     0     0      0
11     0     0     0     0     0     1     0     0      0
12     1     0     0     0     0     0     0     0      0
13     1     0     0     0     0     0     0     0      0
14     0     0     0     1     0     0     0     0      0
15     0     0     1     0     0     0     0     0      0
16     0     0     0     0     0     1     0     0      0
17     0     0     1     0     0     0     0     0      0
18     0     1     0     0     0     0     0     0      0
19     0     0     0     0     0     0     0     1      0

In [76]:
df['C1']>df.C1.mean()

0     False
1      True
2      True
3     False
4     False
5      True
6      True
7     False
8      True
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16     True
17    False
18    False
19     True
Name: C1, dtype: bool

In [77]:
df['h_l']=np.where(df['C1']>df.C1.mean(),'high','low')

In [78]:
df

C1 C2  C1_bin   h_l
0  -0.138264  a       5   low
1   0.647689  a       7  high
2   1.523030  a       9  high
3  -0.234153  a       5   low
4  -0.234137  a       5   low
5   1.579213  a      10  high
6   0.767435  a       7  high
7  -0.469474  a       4   low
8   0.542560  a       7  high
9  -0.463418  a       4   low
10 -0.465730  b       4   low
11  0.241962  b       6  high
12 -1.913280  b       1   low
13 -1.724918  b       1   low
14 -0.562288  b       4   low
15 -1.012831  b       3   low
16  0.314247  b       6  high
17 -0.908024  b       3   low
18 -1.412304  b       2   low
19  1.465649  b       9  high

In [79]:
df.groupby('h_l')

In [83]:
df.groupby('h_l')['C1'].mean()

h_l
high    0.885223
low    -0.794902
Name: C1, dtype: float64

In [86]:
q1=np.percentile(df['C1'],25)

In [87]:
q3=np.percentile(df['C1'],75)

In [90]:
df['h_m_l']=np.where(df['C1']<=q1,'l','h')
df

C1 C2  C1_bin   h_l h_m_l
0  -0.138264  a       5   low     h
1   0.647689  a       7  high     h
2   1.523030  a       9  high     h
3  -0.234153  a       5   low     h
4  -0.234137  a       5   low     h
5   1.579213  a      10  high     h
6   0.767435  a       7  high     h
7  -0.469474  a       4   low     h
8   0.542560  a       7  high     h
9  -0.463418  a       4   low     h
10 -0.465730  b       4   low     h
11  0.241962  b       6  high     h
12 -1.913280  b       1   low     l
13 -1.724918  b       1   low     l
14 -0.562288  b       4   low     h
15 -1.012831  b       3   low     l
16  0.314247  b       6  high     h
17 -0.908024  b       3   low     l
18 -1.412304  b       2   low     l
19  1.465649  b       9  high     h

In [93]:
df['h_m_l']=np.where(df['C1']>=q3,'h',np.where(df['C1']>=q1,'m','l'))

In [94]:
df

C1 C2  C1_bin   h_l h_m_l
0  -0.138264  a       5   low     m
1   0.647689  a       7  high     h
2   1.523030  a       9  high     h
3  -0.234153  a       5   low     m
4  -0.234137  a       5   low     m
5   1.579213  a      10  high     h
6   0.767435  a       7  high     h
7  -0.469474  a       4   low     m
8   0.542560  a       7  high     m
9  -0.463418  a       4   low     m
10 -0.465730  b       4   low     m
11  0.241962  b       6  high     m
12 -1.913280  b       1   low     l
13 -1.724918  b       1   low     l
14 -0.562288  b       4   low     m
15 -1.012831  b       3   low     l
16  0.314247  b       6  high     m
17 -0.908024  b       3   low     l
18 -1.412304  b       2   low     l
19  1.465649  b       9  high     h

In [96]:
data = pd.DataFrame({'cust_id': ['c1', 'c1', 'c1', 'c2', 'c2', 'c2', 'c3', 'c3', 'c3'],

   'prod_cd': ['p1', 'p2', 'p3', 'p1', 'p2', 'p3', 'p1', 'p2', 'p3'],
'grade' : ['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B'],

   'pch_amt': [30, 10, 0, 40, 15, 30, 0, 0, 10]})

In [97]:
data

cust_id prod_cd grade  pch_amt
0      c1      p1     A       30
1      c1      p2     A       10
2      c1      p3     A        0
3      c2      p1     A       40
4      c2      p2     A       15
5      c2      p3     A       30
6      c3      p1     B        0
7      c3      p2     B        0
8      c3      p3     B       10

In [98]:

data.pivot(index='cust_id',columns='prod_cd',values='pch_amt')

prod_cd  p1  p2  p3
cust_id            
c1       30  10   0
c2       40  15  30
c3        0   0  10

In [100]:
pd.pivot_table(data,index='cust_id',columns='prod_cd',values='pch_amt')

prod_cd  p1  p2  p3
cust_id            
c1       30  10   0
c2       40  15  30
c3        0   0  10

In [103]:

pd.pivot_table(data,index=['cust_id','grade'],columns='prod_cd',values='pch_amt')

prod_cd        p1  p2  p3
cust_id grade            
c1      A      30  10   0
c2      A      40  15  30
c3      B       0   0  10

In [105]:
pd.pivot_table(data,index='cust_id',columns=['grade','prod_cd'],values='pch_amt')

grade       A                B           
prod_cd    p1    p2    p3   p1   p2    p3
cust_id                                  
c1       30.0  10.0   0.0  NaN  NaN   NaN
c2       40.0  15.0  30.0  NaN  NaN   NaN
c3        NaN   NaN   NaN  0.0  0.0  10.0

In [106]:
pd.pivot_table(data, index='grade',columns='prod_cd',values='pch_amt')

prod_cd    p1    p2    p3
grade                    
A        35.0  12.5  15.0
B         0.0   0.0  10.0

In [107]:
pd.pivot_table(data, index='grade',columns='prod_cd',values='pch_amt',aggfunc=np.mean)

prod_cd    p1    p2    p3
grade                    
A        35.0  12.5  15.0
B         0.0   0.0  10.0

In [108]:

pd.pivot_table(data, index='grade',columns='prod_cd',values='pch_amt',aggfunc=np.sum)

prod_cd  p1  p2  p3
grade              
A        70  25  30
B         0   0  10

In [111]:
mul_index = pd.MultiIndex.from_tuples([('cust_1', '2020'), ('cust_1', '2021'),

   ('cust_2', '2020'), ('cust_2', '2021')])  



data = pd.DataFrame(data=np.arange(16).reshape(4, 4),

   index=mul_index,

   columns=['prd_1', 'prd_2', 'prd_3', 'prd_4'],

   dtype='int')

In [112]:
mul_index

MultiIndex([('cust_1', '2020'),
            ('cust_1', '2021'),
            ('cust_2', '2020'),
            ('cust_2', '2021')],
           )

In [113]:
data

prd_1  prd_2  prd_3  prd_4
cust_1 2020      0      1      2      3
       2021      4      5      6      7
cust_2 2020      8      9     10     11
       2021     12     13     14     15

In [114]:
data.stack()

cust_1  2020  prd_1     0
              prd_2     1
              prd_3     2
              prd_4     3
        2021  prd_1     4
              prd_2     5
              prd_3     6
              prd_4     7
cust_2  2020  prd_1     8
              prd_2     9
              prd_3    10
              prd_4    11
        2021  prd_1    12
              prd_2    13
              prd_3    14
              prd_4    15
dtype: int32

In [115]:
data_std=data.stack()

In [116]:
data_std.index

MultiIndex([('cust_1', '2020', 'prd_1'),
            ('cust_1', '2020', 'prd_2'),
            ('cust_1', '2020', 'prd_3'),
            ('cust_1', '2020', 'prd_4'),
            ('cust_1', '2021', 'prd_1'),
            ('cust_1', '2021', 'prd_2'),
            ('cust_1', '2021', 'prd_3'),
            ('cust_1', '2021', 'prd_4'),
            ('cust_2', '2020', 'prd_1'),
            ('cust_2', '2020', 'prd_2'),
            ('cust_2', '2020', 'prd_3'),
            ('cust_2', '2020', 'prd_4'),
            ('cust_2', '2021', 'prd_1'),
            ('cust_2', '2021', 'prd_2'),
            ('cust_2', '2021', 'prd_3'),
            ('cust_2', '2021', 'prd_4')],
           )

In [118]:
data_std['cust_2']['2020'][['prd_1','prd_2']]

prd_1    8
prd_2    9
dtype: int32

In [119]:
data

prd_1  prd_2  prd_3  prd_4
cust_1 2020      0      1      2      3
       2021      4      5      6      7
cust_2 2020      8      9     10     11
       2021     12     13     14     15

In [121]:
data.ix[['cust_2'],['prd_4']]=None

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [122]:
data

prd_1  prd_2  prd_3  prd_4
cust_1 2020      0      1      2    3.0
       2021      4      5      6    7.0
cust_2 2020      8      9     10    NaN
       2021     12     13     14    NaN

In [123]:
data.stack()

cust_1  2020  prd_1     0.0
              prd_2     1.0
              prd_3     2.0
              prd_4     3.0
        2021  prd_1     4.0
              prd_2     5.0
              prd_3     6.0
              prd_4     7.0
cust_2  2020  prd_1     8.0
              prd_2     9.0
              prd_3    10.0
        2021  prd_1    12.0
              prd_2    13.0
              prd_3    14.0
dtype: float64

In [124]:
data.stack(dropna=False)

cust_1  2020  prd_1     0.0
              prd_2     1.0
              prd_3     2.0
              prd_4     3.0
        2021  prd_1     4.0
              prd_2     5.0
              prd_3     6.0
              prd_4     7.0
cust_2  2020  prd_1     8.0
              prd_2     9.0
              prd_3    10.0
              prd_4     NaN
        2021  prd_1    12.0
              prd_2    13.0
              prd_3    14.0
              prd_4     NaN
dtype: float64

In [125]:
data = pd.DataFrame({'cust_ID' : ['C_001', 'C_001', 'C_002', 'C_002'],

   'prd_CD' : ['P_001', 'P_002', 'P_001', 'P_002'],

   'pch_cnt' : [1, 2, 3, 4],
'pch_amt' : [100, 200, 300, 400]})

In [126]:
data

cust_ID prd_CD  pch_cnt  pch_amt
0   C_001  P_001        1      100
1   C_001  P_002        2      200
2   C_002  P_001        3      300
3   C_002  P_002        4      400

In [127]:
pd.melt(data,id_vars=['cust_ID','prd_CD'])

cust_ID prd_CD variable  value
0   C_001  P_001  pch_cnt      1
1   C_001  P_002  pch_cnt      2
2   C_002  P_001  pch_cnt      3
3   C_002  P_002  pch_cnt      4
4   C_001  P_001  pch_amt    100
5   C_001  P_002  pch_amt    200
6   C_002  P_001  pch_amt    300
7   C_002  P_002  pch_amt    400

In [128]:
pd.melt(data,id_vars=['cust_ID','prd_CD'],var_name='CD',value_name='VAL')

cust_ID prd_CD       CD  VAL
0   C_001  P_001  pch_cnt    1
1   C_001  P_002  pch_cnt    2
2   C_002  P_001  pch_cnt    3
3   C_002  P_002  pch_cnt    4
4   C_001  P_001  pch_amt  100
5   C_001  P_002  pch_amt  200
6   C_002  P_001  pch_amt  300
7   C_002  P_002  pch_amt  400

In [130]:
import numpy as np
import pandas as pd

pew=pd.read_csv('pew.csv')
pew.head()



religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k  $50-75k  \
0            Agnostic     27       34       60       81       76      137   
1             Atheist     12       27       37       52       35       70   
2            Buddhist     27       21       30       34       33       58   
3            Catholic    418      617      732      670      638     1116   
4  Don’t know/refused     15       14       15       11       10       35   

   $75-100k  $100-150k  >150k  Don't know/refused  
0       122        109     84                  96  
1        73         59     74                  76  
2        62         39     53                  54  
3       949        792    633                1489  
4        21         17     18                 116

In [132]:
pew.iloc[:,:6]

religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k
0                  Agnostic     27       34       60       81       76
1                   Atheist     12       27       37       52       35
2                  Buddhist     27       21       30       34       33
3                  Catholic    418      617      732      670      638
4        Don’t know/refused     15       14       15       11       10
5          Evangelical Prot    575      869     1064      982      881
6                     Hindu      1        9        7        9       11
7   Historically Black Prot    228      244      236      238      197
8         Jehovah's Witness     20       27       24       24       21
9                    Jewish     19       19       25       25       30
10            Mainline Prot    289      495      619      655      651
11                   Mormon     29       40       48       51       56
12                   Muslim      6        7        9       10        9
13                 Orthodox     13       17       23       32       32
14          Other Christian      9        7       11       13       13
15             Other Faiths     20       33       40       46       49
16    Other World Religions      5        2        3        4        2
17             Unaffiliated    217      299      374      365      341

In [135]:
pd.melt(pew,id_vars='religion',var_name='count')

religion               count  value
0                 Agnostic               <$10k     27
1                  Atheist               <$10k     12
2                 Buddhist               <$10k     27
3                 Catholic               <$10k    418
4       Don’t know/refused               <$10k     15
..                     ...                 ...    ...
175               Orthodox  Don't know/refused     73
176        Other Christian  Don't know/refused     18
177           Other Faiths  Don't know/refused     71
178  Other World Religions  Don't know/refused      8
179           Unaffiliated  Don't know/refused    597

[180 rows x 3 columns]

In [136]:
billboard=pd.read_csv('billboard.csv')
billboard

year            artist                    track  time date.entered  wk1  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   87   
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   91   
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08   81   
3    2000      3 Doors Down                    Loser  4:24   2000-10-21   76   
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   57   
..    ...               ...                      ...   ...          ...  ...   
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   86   
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   85   
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   95   
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   99   
316  2000   matchbox twenty                     Bent  4:12   2000-04-29   60   

      wk2   wk3   wk4   wk5  ...  wk67  wk68  wk69  wk70  wk71  wk72  wk73  \
0    82.0  72.0  77.0  87.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1    87.0  92.0   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2    70.0  68.0  67.0  66.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3    76.0  72.0  69.0  67.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4    34.0  25.0  17.0  17.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
..    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...   
312  83.0  77.0  74.0  83.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
313  83.0  83.0  82.0  81.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
314  94.0  91.0  85.0  84.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
315  99.0   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
316  37.0  29.0  24.0  22.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

     wk74  wk75  wk76  
0     NaN   NaN   NaN  
1     NaN   NaN   NaN  
2     NaN   NaN   NaN  
3     NaN   NaN   NaN  
4     NaN   NaN   NaN  
..    ...   ...   ...  
312   NaN   NaN   NaN  
313   NaN   NaN   NaN  
314   NaN   NaN   NaN  
315   NaN   NaN   NaN  
316   NaN   NaN   NaN  

[317 rows x 81 columns]

In [140]:
pd.melt(billboard,id_vars=['year','artist','track','time','date.entered'],var_name='week',value_name='rating')

year            artist                    track  time date.entered  \
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
1      2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   
2      2000      3 Doors Down               Kryptonite  3:53   2000-04-08   
3      2000      3 Doors Down                    Loser  4:24   2000-10-21   
4      2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   
...     ...               ...                      ...   ...          ...   
24087  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   
24088  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   
24090  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   
24091  2000   matchbox twenty                     Bent  4:12   2000-04-29   

       week  rating  
0       wk1    87.0  
1       wk1    91.0  
2       wk1    81.0  
3       wk1    76.0  
4       wk1    57.0  
...     ...     ...  
24087  wk76     NaN  
24088  wk76     NaN  
24089  wk76     NaN  
24090  wk76     NaN  
24091  wk76     NaN  

[24092 rows x 7 columns]

In [141]:
import numpy as np
import pandas as pd

s=pd.Series(range(10))
s[3]=np.nan

In [142]:
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [144]:
s.count()

9

In [146]:
df=pd.DataFrame(np.random.randint(5,size=(4,4)),dtype=float)
df

0    1    2    3
0  2.0  3.0  3.0  0.0
1  2.0  4.0  2.0  4.0
2  0.0  1.0  3.0  0.0
3  3.0  1.0  1.0  0.0

In [148]:
df.ix[2,3]=None
df

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


0    1    2    3
0  2.0  3.0  3.0  0.0
1  2.0  4.0  2.0  4.0
2  0.0  1.0  3.0  NaN
3  3.0  1.0  1.0  0.0

In [149]:
df.count()

0    4
1    4
2    4
3    3
dtype: int64

In [151]:
import seaborn as sns
titanic=sns.load_dataset('titanic')
titanic.head()
titanic.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [157]:
np.random.seed(777)
s2=pd.Series(np.random.randint(6,size=100))
s2.value_counts()

5    20
0    20
4    19
3    15
2    15
1    11
dtype: int64

In [158]:
df[0].value_counts()

2.0    2
3.0    1
0.0    1
Name: 0, dtype: int64

In [161]:
s2.value_counts().sort_index()

0    20
1    11
2    15
3    15
4    19
5    20
dtype: int64

In [162]:
s.sort_values()

0    0.0
1    1.0
2    2.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
3    NaN
dtype: float64

In [166]:
df.sort_values(by=[1,2])

0    1    2    3
3  3.0  1.0  1.0  0.0
2  0.0  1.0  3.0  NaN
0  2.0  3.0  3.0  0.0
1  2.0  4.0  2.0  4.0

In [174]:
df=pd.DataFrame(np.random.randint(10,size=(4,8)))
df['Mysum']=df.sum(axis=1)
df.loc['total',:]=df.sum()
df

0     1     2     3     4     5     6     7  Mysum
0       1.0   7.0   5.0   1.0   0.0   3.0   2.0   6.0   25.0
1       4.0   7.0   0.0   6.0   4.0   2.0   8.0   6.0   37.0
2       1.0   6.0   7.0   0.0   8.0   3.0   0.0   4.0   29.0
3       9.0   6.0   7.0   4.0   5.0   6.0   2.0   8.0   47.0
total  15.0  26.0  19.0  11.0  17.0  14.0  12.0  24.0  138.0

In [176]:
import numpy as np
import pandas as pd

ages=[0,2,10,21,23,37,31,61,20,42,32,100]
labels=['미성년자','청년','중년','장년','노년']
bins=[1,15,25,35,60,99]


In [182]:
cats=pd.cut(ages, bins, labels=labels)
cats

[NaN, 미성년자, 미성년자, 청년, 청년, ..., 노년, 청년, 장년, 중년, NaN]
Length: 12
Categories (5, object): [미성년자 < 청년 < 중년 < 장년 < 노년]

In [180]:
cats.codes

array([-1,  0,  0,  1,  1,  3,  2,  4,  1,  3,  2, -1], dtype=int8)

In [181]:
cats.categories

Index(['미성년자', '청년', '중년', '장년', '노년'], dtype='object')

In [184]:
df=pd.DataFrame(ages,columns=['ages'])

In [186]:
df['age_cat']=pd.cut(ages, bins, labels=labels)
df

ages age_cat
0      0     NaN
1      2    미성년자
2     10    미성년자
3     21      청년
4     23      청년
5     37      장년
6     31      중년
7     61      노년
8     20      청년
9     42      장년
10    32      중년
11   100     NaN

In [187]:
data=np.random.randn(100)
data

array([ 1.38966579, -0.91661992, -0.48610178,  1.48125082,  0.55047957,
        1.34857875, -0.35551272, -1.21833495,  0.01649681, -1.68720567,
        0.08243204,  1.75207268,  0.95508062,  0.79534453,  0.48871851,
       -1.26382399,  0.82114657, -0.37744485, -0.39078377, -1.1615458 ,
       -0.09795812,  3.10015157, -0.77534415, -0.15853073,  2.11697247,
        0.11795774,  0.30158328,  1.61232547, -0.31692054,  0.19679875,
       -0.41147716,  1.26086425,  0.51111147, -0.86125485, -2.57423814,
        1.21332657, -0.91835996, -0.42676877,  1.19313492,  0.99792732,
       -0.22368386,  0.32584174,  0.43662589, -0.45915999,  1.49805923,
       -0.68966659,  0.3632098 ,  0.54195504,  0.67195194,  0.58804143,
        0.76686843,  0.70278761,  0.6064141 , -2.30411292, -0.37085518,
       -0.61997229, -1.56022681,  0.30242317, -1.39506269,  0.00383393,
       -1.64577533,  1.22211456,  1.40299575, -1.42429013, -0.07318308,
        1.48855629,  0.73473802,  0.37548408, -0.37148146,  1.21

In [191]:
cats=pd.qcut(data,4,labels=['q1','q2','q3','q4'])

In [192]:
pd.value_counts(cats)

q4    25
q3    25
q2    25
q1    25
dtype: int64

In [197]:
import seaborn as sns
titanic=sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [211]:
import numpy as np
import pandas as pd

bins=np.linspace(titanic.age.min(),titanic.age.max(),5)
bins

bins2=np.linspace(titanic.fare.min(),titanic.fare.max(),3)
bins2

from sklearn.preprocessing import OneHotEncoder 


In [217]:
bins = [1, 15, 25, 35, 60, 99]
labels = ["미성년자", "청년", "중년", "장년", "노년"]

cuts=pd.melt(titanic,id_vars='survived')

ages=titanic.ix[:,3]

cats=pd.cut(ages, bins, labels=labels)
cats

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  


0       청년
1       장년
2       중년
3       중년
4       중년
      ... 
886     중년
887     청년
888    NaN
889     중년
890     중년
Name: age, Length: 891, dtype: category
Categories (5, object): [미성년자 < 청년 < 중년 < 장년 < 노년]

In [219]:
cats.value_counts(normalize=True)

청년      0.311429
중년      0.280000
장년      0.278571
미성년자    0.098571
노년      0.031429
Name: age, dtype: float64

In [227]:
import pandas as pd
import numpy as np
ns = [1, 3, 5, 1, 3, 5, 1, 3, 5]
ns=np.reshape(ns,(3,3))
ns.drop_duplicates()

AttributeError: 'numpy.ndarray' object has no attribute 'drop_duplicates'