In [1]:
import pandas as pd
import numpy as np

In [2]:
#array에 축 추가  np.newaxis  np.tile()

a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a.shape

(4,)

In [4]:
a41=a[:,np.newaxis]
a41

array([[1],
       [2],
       [3],
       [4]])

In [6]:
a14=a[np.newaxis,:]
a14

array([[1, 2, 3, 4]])

In [7]:
b=np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
b351=b[:,:,np.newaxis]
b351.shape

(3, 5, 1)

In [10]:
b315=b[:,np.newaxis,:]
b315.shape

(3, 1, 5)

In [12]:
c=np.array([0,1,2,3])
c8=np.tile(c,2)
c8

array([1, 2, 3, 4, 1, 2, 3, 4])

In [13]:
c32=np.tile(c,(3,2))
c32

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3]])

In [14]:
d=np.arange(8).reshape(2,4)
d28=np.tile(d,2)
d28

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7]])

In [15]:
d44=np.tile(d,(2,1))
d44

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
#vector 내적 : aT * a
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [18]:
np.transpose(a)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [21]:
b=np.arange(10)
bi=b[:5]
bi[1:3]=10


array([ 0, 10, 10,  3,  4,  5,  6,  7,  8,  9])

In [22]:
arr=np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
abc=np.array(['a','a','b','c','c'])
abc

array(['a', 'a', 'b', 'c', 'c'], dtype='<U1')

In [24]:
abc=='a'

array([ True,  True, False, False, False])

In [25]:
arr[abc=='a']

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
arr[abc=='a',:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
arr[abc=='a',:2]

array([[0, 1],
       [4, 5]])

In [28]:
arr[abc=='a',2]

array([2, 6])

In [29]:
arr[abc!='a']

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
arr[~(abc=='a')]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [31]:
arr[(abc=='a') | (abc=='b')]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
arr[(abc!='a') & (abc!='b')]

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
arr[abc=='a']=99
arr

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [35]:
arr[arr>20]=0
arr

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [38]:
arr[(arr>=8) & (arr<=15)]=10
arr

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [16, 17, 18, 19]])

In [39]:
a=np.array([-3.5,-2.2,0,1.6,3.14,4.05])
np.around(a)  # 0.5 기준 올림/내림

array([-4., -2.,  0.,  2.,  3.,  4.])

In [40]:
np.round_(a,1)  # 소수 이하 첫째자리까지

array([-3.5, -2.2,  0. ,  1.6,  3.1,  4. ])

In [41]:
np.rint(a)  #가까운 정수로 올림/내림

array([-4., -2.,  0.,  2.,  3.,  4.])

In [42]:
np.fix(a)  # 0에 가까운 정수로 올림/내림

array([-3., -2.,  0.,  1.,  3.,  4.])

In [43]:
np.ceil(a)  # 크거나 같은 가장 작은 정수값으로 올림

array([-3., -2.,  0.,  2.,  4.,  5.])

In [44]:
np.floor(a)  #작거나 같은 가장 큰 정수값으로 내림 = 가우스

array([-4., -3.,  0.,  1.,  3.,  4.])

In [73]:
np.trunc(a)  # 소숫점 이하 버림, 정수만 출력a=np.array([-3.5,-2.2,0,1.6,3.14,4.05])


array([-3., -2.,  0.,  1.,  3.,  4.])

In [50]:
# 배열 요소 곱셉

b=np.array([1,2,3,4])
c=np.arange(1,5).reshape(2,2)

np.prod(b)

24

In [51]:
np.prod(c,axis=0)  # column 기준 곱셈

array([3, 8])

In [52]:
np.prod(c,axis=1)  # row 기준 곱셈

array([ 2, 12])

In [53]:
c

array([[1, 2],
       [3, 4]])

In [54]:
np.sum(b)

10

In [55]:
np.sum(b,keepdims=True)  # 차원 유지 

array([10])

In [56]:
np.sum(c,axis=0)

array([4, 6])

In [57]:
np.sum(c,axis=1)

array([3, 7])

In [61]:
d=np.array([[1,2],[3,np.nan]])
d

array([[ 1.,  2.],
       [ 3., nan]])

In [62]:
np.prod(d)

nan

In [63]:
np.prod(d,axis=0)

array([ 3., nan])

In [64]:
np.prod(d,axis=1)

array([ 2., nan])

In [65]:
np.nanprod(d,axis=0)   # nan=1 취급

array([3., 2.])

In [66]:
np.sum(d)

nan

In [67]:
np.nansum(d)   # nan=0 취급

6.0

In [69]:
e=np.arange(1,7).reshape(2,3)
e

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
np.cumprod(b)   #누적 곱셉

array([ 1,  2,  6, 24], dtype=int32)

In [71]:
np.cumprod(e,axis=0)   # column별 누적 곱셈

array([[ 1,  2,  3],
       [ 4, 10, 18]], dtype=int32)

In [72]:
np.cumprod(e,axis=1) 

array([[  1,   2,   6],
       [  4,  20, 120]], dtype=int32)

In [77]:
np.cumsum(b)

array([ 1,  3,  6, 10], dtype=int32)

In [74]:
#밑이 자연상수 e인 지수함수  np.exp()  

x=np.array([0.00001,1,2,10])
np.exp(x)

array([1.00001000e+00, 2.71828183e+00, 7.38905610e+00, 2.20264658e+04])

In [79]:
# 밑이 n인 로그함수  np.logn()

#np.log(x)
np.log10(x)

array([-5.     ,  0.     ,  0.30103,  1.     ])

In [85]:
# bin()
# int('0b101010', 2)
# np.ceil(a)  # 크거나 같은 가장 작은 정수값으로 올림

data=int(input())
    
def f(data):
    for data in range(1,1000):
        onenum=string(bin(data)).count('1')
        
    
    

75
[1 2 3 4]
