In [3]:
import nltk 
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [4]:
import konlpy
konlpy.__version__

'0.5.2'

In [17]:
# 단어토큰화 - 구두점/특수문자 제거, 

from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from nltk.tokenize import TreebankWordTokenizer
from nltk.tokenize import sent_tokenize
from nltk.tag import pos_tag
from konlpy.tag import Okt

C:\Users\student\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\student\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [7]:
print(word_tokenize("Mr.Jacob's Don't be"))

['Mr.Jacob', "'s", 'Do', "n't", 'be']


In [9]:
print(WordPunctTokenizer().tokenize("Mr.Jacob's Don't be"))

['Mr', '.', 'Jacob', "'", 's', 'Don', "'", 't', 'be']


In [11]:
# 대문자->소문자, 특수문자 제거, 
print(text_to_word_sequence("Mr.Jacob's Don't be"))

['mr', "jacob's", "don't", 'be']


In [18]:
twt=TreebankWordTokenizer()
print(TreebankWordTokenizer().tokenize("Mr.Jacob's Don't be"))

['Mr.Jacob', "'s", 'Do', "n't", 'be']


In [18]:
# 문장토큰화
text="Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects."
print(sent_tokenize(text))

['Python is an interpreted, high-level, general-purpose programming language.', "Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace.", 'Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.']


In [24]:
## korean 형태소 토큰화
# 조사, 띄어쓰기, 형태소
# okt, mecab, kkma
okt=Okt()
# okt.morphs() -> 형태소 추출
print(okt.morphs("오늘은 수요일, 내일은 목요일입니다."))
# okt.pos() -> 품사 추출
print(okt.pos("오늘은 수요일, 내일은 목요일입니다."))
# okt.nouns() -> 명사 추출
print(okt.nouns("오늘은 수요일, 내일은 목요일입니다."))

['오늘', '은', '수요일', ',', '내일', '은', '목요일', '입니다', '.']
[('오늘', 'Noun'), ('은', 'Josa'), ('수요일', 'Noun'), (',', 'Punctuation'), ('내일', 'Noun'), ('은', 'Josa'), ('목요일', 'Noun'), ('입니다', 'Adjective'), ('.', 'Punctuation')]
['오늘', '수요일', '내일', '목요일']


In [ ]:
# 토큰화된 데이터 전처리 - 형태소 제거, 단어 통일
# 정규표현식 이용  ex) \w{1,2}

In [21]:
# 품사 tagging - 단어가 어떤 품사로 쓰였는지 구분
text="Python is an interpreted, high-level, general-purpose programming language."
print(word_tokenize(text))

pos_tag(word_tokenize(text))

['Python', 'is', 'an', 'interpreted', ',', 'high-level', ',', 'general-purpose', 'programming', 'language', '.']


[('Python', 'NNP'),
 ('is', 'VBZ'),
 ('an', 'DT'),
 ('interpreted', 'JJ'),
 (',', ','),
 ('high-level', 'JJ'),
 (',', ','),
 ('general-purpose', 'JJ'),
 ('programming', 'NN'),
 ('language', 'NN'),
 ('.', '.')]

In [ ]:
### SVD (특이값 분해)

In [27]:
import numpy as np

In [28]:
a=np.array([[0,0,0,1,0,1,1,0,0],
          [0,0,0,1,1,0,1,0,0],
          [0,1,1,0,2,0,0,0,0],
          [1,0,0,0,0,0,0,1,1]])

In [29]:
np.shape(a)

(4, 9)

In [40]:
## full svd
U, s, VT=np.linalg.svd(a,full_matrices=True)

In [39]:
U.round(2)

array([[-0.24,  0.75,  0.  , -0.62],
       [-0.51,  0.44, -0.  ,  0.74],
       [-0.83, -0.49, -0.  , -0.27],
       [-0.  , -0.  ,  1.  ,  0.  ]])

In [42]:
s.round(2)

array([2.69, 2.05, 1.73, 0.77])

In [45]:
# 특이값 행렬
S=np.zeros((4,9))
S[:4,:4]=np.diag(s)
S.round(2)

array([[2.69, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 2.05, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.73, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.77, 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [46]:
VT.round(2)

array([[-0.  , -0.31, -0.31, -0.28, -0.8 , -0.09, -0.28, -0.  , -0.  ],
       [ 0.  , -0.24, -0.24,  0.58, -0.26,  0.37,  0.58, -0.  , -0.  ],
       [ 0.58, -0.  ,  0.  ,  0.  , -0.  ,  0.  , -0.  ,  0.58,  0.58],
       [ 0.  , -0.35, -0.35,  0.16,  0.25, -0.8 ,  0.16, -0.  , -0.  ],
       [-0.  , -0.78, -0.01, -0.2 ,  0.4 ,  0.4 , -0.2 ,  0.  ,  0.  ],
       [-0.29,  0.31, -0.78, -0.24,  0.23,  0.23,  0.01,  0.14,  0.14],
       [-0.29, -0.1 ,  0.26, -0.59, -0.08, -0.08,  0.66,  0.14,  0.14],
       [-0.5 , -0.06,  0.15,  0.24, -0.05, -0.05, -0.19,  0.75, -0.25],
       [-0.5 , -0.06,  0.15,  0.24, -0.05, -0.05, -0.19, -0.25,  0.75]])

In [49]:
np.dot((np.dot(U,S)),VT).round(2)

array([[ 0.,  0.,  0.,  1., -0.,  1.,  1.,  0.,  0.],
       [ 0., -0., -0.,  1.,  1., -0.,  1., -0., -0.],
       [ 0.,  1.,  1., -0.,  2., -0., -0.,  0.,  0.],
       [ 1., -0.,  0.,  0., -0.,  0., -0.,  1.,  1.]])

In [50]:
np.allclose(a,np.dot((np.dot(U,S)),VT).round(2))

True

In [51]:
## truncated svd
S=S[:2,:2]
S.round(2)

array([[2.69, 0.  ],
       [0.  , 2.05]])

In [52]:
# U=4개 문서 각각에 대한 잠재의미를 나타내는 수치문서 vector
U=U[:,:2]  
U.round(2)

array([[-0.24,  0.75],
       [-0.51,  0.44],
       [-0.83, -0.49],
       [-0.  , -0.  ]])

In [53]:
# VT = 토픽*잠재의미를 나타내는 수치화된 단어 vector
VT=VT[:2,:]
VT.round(2)

array([[-0.  , -0.31, -0.31, -0.28, -0.8 , -0.09, -0.28, -0.  , -0.  ],
       [ 0.  , -0.24, -0.24,  0.58, -0.26,  0.37,  0.58, -0.  , -0.  ]])

In [54]:
a_prime=np.dot(np.dot(U,S),VT)
a_prime.round(2)

array([[ 0.  , -0.17, -0.17,  1.08,  0.12,  0.62,  1.08, -0.  , -0.  ],
       [ 0.  ,  0.2 ,  0.2 ,  0.91,  0.86,  0.45,  0.91,  0.  ,  0.  ],
       [ 0.  ,  0.93,  0.93,  0.03,  2.05, -0.17,  0.03,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.  ,  0.  ,  0.  ,  0.  ]])

In [55]:
np.dot(S,VT).round(2)

array([[-0.  , -0.83, -0.83, -0.75, -2.16, -0.24, -0.75, -0.  , -0.  ],
       [ 0.  , -0.49, -0.49,  1.2 , -0.53,  0.75,  1.2 , -0.  , -0.  ]])

In [56]:
from numpy.linalg import norm

In [57]:
m1=np.array([0,1,1,1])
m2=np.array([1,0,1,1])
m3=np.array([2,0,2,2])

In [63]:
# cos 유사도
def cos_sim(x,y):
    return np.dot(x,y) / (norm(x)*norm(y))

print(cos_sim(m1,m2))
print(cos_sim(m2,m3))
print(cos_sim(m1,m3))

0.6666666666666667
1.0000000000000002
0.6666666666666667


In [ ]:
# 표제어(lemmatization)  추출   ->  형태는 다르지만 root 단어가 같은 단어들을 축소
# WordNetLemmatizer

In [1]:
from nltk.stem import WordNetLemmatizer
wnl=WordNetLemmatizer()

In [7]:
# WordNetLemmatizer().lemmatize('단어', '품사')
print(wnl.lemmatize('watched', 'v'))
print(wnl.lemmatize('has', 'v'))

watch
have


In [ ]:
# 어간(stem) 추출 

In [12]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize


# 1) PorterStemmer().stem()
ps=PorterStemmer()
text="Python is an interpreted, high-level, general-purpose programming language."
word_tk=word_tokenize(text)

print([ps.stem(w) for w in word_tk])

print(ps.stem('electricical'))
print(ps.stem('formalize'))
print(ps.stem('gone'))

['python', 'is', 'an', 'interpret', ',', 'high-level', ',', 'general-purpos', 'program', 'languag', '.']
electric
formal
gone


In [53]:
from nltk.stem import LancasterStemmer
ls=LancasterStemmer()

# 2) LancasterStemmer().stem()
print(ls.stem('electricical'))
print(ls.stem('formalize'))
print(ls.stem('gone'))
print(ls.stem('going'))

print([ls.stem(w) for w in word_tk])

elect
form
gon
going
['python', 'is', 'an', 'interpret', ',', 'high-level', ',', 'general-purpose', 'program', 'langu', '.']


In [16]:
# 불용어(stopwords) 처리
# stopwords.words()
from nltk.corpus import stopwords
stopwords=stopwords.words('english')
res=[]
ex="Family is not an important thing. It's everything."
ex_tk=word_tokenize(ex)
for word in ex_tk:
    if word not in stopwords:
        res.append(word)
print(ex_tk)
print(res)        

['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


In [20]:
# 한국어 불용어 처리
from nltk.tokenize import word_tokenize
ex='최근 코로나 19 감염으로 인해 확진자 및 사망자가 증가하고 있습니다. 코로나19를 이겨냅시다'
kor_stopwords='인해 및 하고 있습니다'
kor_stopwords=kor_stopwords.split(" ")

res=[]
for word in word_tokenize(ex):
    if word not in kor_stopwords:
        res.append(word)
print(res)

['최근', '코로나', '19', '감염으로', '확진자', '사망자가', '증가하고', '.', '코로나19를', '이겨냅시다']


In [42]:

## 1) 문장 토큰화
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
text="Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects."
text_tk=sent_tokenize(text)

## 2) 문장 ->  단어  토큰화

stopwords=stopwords.words('english')
worddict={}
sentences_tk=[]

for t in text_tk:
    words_tk=word_tokenize(t)
    wordlist=[]
    for word in words_tk:
        # 소문자
        word=word.lower()
        # 불용어 제거
        if word not in stopwords:
            # 길이 2 이하 단어 제거
            if len(word)>2:
                wordlist.append(word)
                # 토큰화된 단어 갯수 세기
                if word not in worddict:
                    worddict[word]=0
                worddict[word]+=1
    # 문장별 단어 토큰화            
    sentences_tk.append(wordlist)
print(wordlist) 
print(worddict)
print(sentences_tk)

['language', 'constructs', 'object-oriented', 'approach', 'aim', 'help', 'programmers', 'write', 'clear', 'logical', 'code', 'small', 'large-scale', 'projects']
{'python': 2, 'interpreted': 1, 'high-level': 1, 'general-purpose': 1, 'programming': 1, 'language': 2, 'created': 1, 'guido': 1, 'van': 1, 'rossum': 1, 'first': 1, 'released': 1, '1991': 1, 'design': 1, 'philosophy': 1, 'emphasizes': 1, 'code': 2, 'readability': 1, 'notable': 1, 'use': 1, 'significant': 1, 'whitespace': 1, 'constructs': 1, 'object-oriented': 1, 'approach': 1, 'aim': 1, 'help': 1, 'programmers': 1, 'write': 1, 'clear': 1, 'logical': 1, 'small': 1, 'large-scale': 1, 'projects': 1}
[['python', 'interpreted', 'high-level', 'general-purpose', 'programming', 'language'], ['created', 'guido', 'van', 'rossum', 'first', 'released', '1991', 'python', 'design', 'philosophy', 'emphasizes', 'code', 'readability', 'notable', 'use', 'significant', 'whitespace'], ['language', 'constructs', 'object-oriented', 'approach', 'aim'

In [56]:
# 토큰화된 단어 갯수별 정렬
print(sorted(worddict.items(),key=lambda x:x[1],reverse=True))

[('python', 2), ('language', 2), ('code', 2), ('interpreted', 1), ('high-level', 1), ('general-purpose', 1), ('programming', 1), ('created', 1), ('guido', 1), ('van', 1), ('rossum', 1), ('first', 1), ('released', 1), ('1991', 1), ('design', 1), ('philosophy', 1), ('emphasizes', 1), ('readability', 1), ('notable', 1), ('use', 1), ('significant', 1), ('whitespace', 1), ('constructs', 1), ('object-oriented', 1), ('approach', 1), ('aim', 1), ('help', 1), ('programmers', 1), ('write', 1), ('clear', 1), ('logical', 1), ('small', 1), ('large-scale', 1), ('projects', 1)]


In [57]:
# 토큰화된 단어 기준 정렬
print(sorted(worddict.items(),key=lambda x:x[0],reverse=True))

[('write', 1), ('whitespace', 1), ('van', 1), ('use', 1), ('small', 1), ('significant', 1), ('rossum', 1), ('released', 1), ('readability', 1), ('python', 2), ('projects', 1), ('programming', 1), ('programmers', 1), ('philosophy', 1), ('object-oriented', 1), ('notable', 1), ('logical', 1), ('large-scale', 1), ('language', 2), ('interpreted', 1), ('high-level', 1), ('help', 1), ('guido', 1), ('general-purpose', 1), ('first', 1), ('emphasizes', 1), ('design', 1), ('created', 1), ('constructs', 1), ('code', 2), ('clear', 1), ('approach', 1), ('aim', 1), ('1991', 1)]


In [34]:
# 정렬 list에 index 추가하기
# vs=sorted(worddict.items(),key=lambda x:x[1],reverse=True)
# wordfreq={}
# i=0

# for w,f in vs:
#     if f>1:
#         i+=1
#         wordfreq[w]=i
# print(wordfreq)

vs=sorted(worddict.items(),key=lambda x:x[1],reverse=True)

for w,f in vs:
  print(w,f)

python 2
language 2
code 2
interpreted 1
high-level 1
general-purpose 1
programming 1
created 1
guido 1
van 1
rossum 1
first 1
released 1
1991 1
design 1
philosophy 1
emphasizes 1
readability 1
notable 1
use 1
significant 1
whitespace 1
constructs 1
object-oriented 1
approach 1
aim 1
help 1
programmers 1
write 1
clear 1
logical 1
small 1
large-scale 1
projects 1


In [36]:
# 정렬 list에 index 추가하기
vs=sorted(worddict.items(),key=lambda x:x[1],reverse=True)
wordcount={}
i=0

for w,f in vs:
    if f>1:
        i+=1
        wordcount[w]=i
print(wordcount)

{'python': 1, 'language': 2, 'code': 3}


In [58]:
# 가장 많이 언급된 단어 2개/index 출력
rank=2
wordfreq=[w for w,i in wordcount.items() if i>rank]
# print(wordfreq)
for w in wordfreq:
    del wordcount[w]
    
print(wordcount)

{'python': 1, 'language': 2}


In [ ]:
## OOV (out of vocabulary)

In [51]:
#### 한국어 원핫인코딩
from konlpy.tag import Okt
okt=Okt()
kor_tk=okt.morphs('나는 자연어 처리를 학습한다')

kor_index={}

for v in kor_tk:
    if v not in kor_index.keys():
        kor_index[v]=len(kor_index)

    
def ohe(w,kor_index):
    ohv=[0]*len(kor_index)
    index=kor_index[w]
    ohv[index]=1
    return ohv
    
ohe("자연어", kor_index)

[0, 0, 1, 0, 0, 0, 0]

In [47]:
## keras 활용 원핫인코딩
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
tk=Tokenizer()

text='데이터 분석은 판다스 최고야 판다스 곰이야'
tk.fit_on_texts([text])

#  단어집합 출력
print(tk.word_index)

{'판다스': 1, '데이터': 2, '분석은': 3, '최고야': 4, '곰이야': 5}


In [48]:
# 단어집합에서 
text2='판다스 분석은 동물원에서 한다'
tk.texts_to_sequences([text2])

[[1, 3]]

In [49]:
# 원핫인코딩
enc=tk.texts_to_sequences([text2])[0]
to_categorical(enc)

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [65]:
import pandas as pd

In [121]:
path=r'C:\\Users\\student\\Desktop\\공부\\멀캠TIL\\dataset\\python\\the-movies-dataset'

data=pd.read_csv(path+'\\movies_metadata.csv')

C:\Users\student\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [122]:
# data['overview'].isnull().sum()
# 결측값  처리
data['overview']=data['overview'].fillna('')

In [127]:
data.head(3)

adult                              belongs_to_collection    budget  ...  video vote_average vote_count
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000  ...  False          7.7     5415.0
1  False                                                NaN  65000000  ...  False          6.9     2413.0
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0  ...  False          6.5       92.0

[3 rows x 24 columns]

In [123]:
#  tf-idf
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(stop_words='english')
tfidf_mat=tfidf.fit_transform(data['overview'])
tfidf_mat.shape

(45466, 75827)

In [129]:
def cos_sim(x,y):
    return np.dot(x,y) / (norm(x)*norm(y))
cos_sim=cos_sim(tfidf_mat,tfidf_mat)

ValueError: dimension mismatch

In [128]:
movie_title=pd.Series(data.index, index=data.title).drop_duplicates()

In [98]:
def movie_recommendation(title,simf=cos_sin):
    movie_index=movie_title.title
    
    sim_scores=list(enumerate(cos_sim(movie_index)))
    

overview    Led by Woody, Andy's toys live happily in his ...
Name: 0, dtype: object